/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author ahmed
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        makealltransparent();
    }

    public void makealltransparent() {
        manageadminsbtn.setOpaque(false);
        managemanagersbtn.setOpaque(false);
        managecompaniesbtn.setOpaque(false);
        manageauthorsbtn.setOpaque(false);
        managecustomersbtn.setOpaque(false);
        accountdetailsbtn.setOpaque(false);
        signoutbtn.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageadminsbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        managemanagersbtn = new javax.swing.JButton();
        managecompaniesbtn = new javax.swing.JButton();
        manageauthorsbtn = new javax.swing.JButton();
        managecustomersbtn = new javax.swing.JButton();
        signoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        accountdetailsbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageadminsbtn.setBackground(new java.awt.Color(102, 0, 102));
        manageadminsbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        manageadminsbtn.setForeground(new java.awt.Color(204, 204, 255));
        manageadminsbtn.setText("Manage Admins Accounts");
        jPanel1.add(manageadminsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Main Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 12, -1, 52));

        managemanagersbtn.setBackground(new java.awt.Color(102, 0, 102));
        managemanagersbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        managemanagersbtn.setForeground(new java.awt.Color(204, 204, 255));
        managemanagersbtn.setText("Manage Managers Accounts");
        jPanel1.add(managemanagersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 273, -1, -1));

        managecompaniesbtn.setBackground(new java.awt.Color(102, 0, 102));
        managecompaniesbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        managecompaniesbtn.setForeground(new java.awt.Color(204, 204, 255));
        managecompaniesbtn.setText("Manage Companies Accounts");
        jPanel1.add(managecompaniesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 145, -1, -1));

        manageauthorsbtn.setBackground(new java.awt.Color(102, 0, 102));
        manageauthorsbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        manageauthorsbtn.setForeground(new java.awt.Color(204, 204, 255));
        manageauthorsbtn.setText("Manage Blog authors Accounts");
        jPanel1.add(manageauthorsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 209, -1, -1));

        managecustomersbtn.setBackground(new java.awt.Color(102, 0, 102));
        managecustomersbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        managecustomersbtn.setForeground(new java.awt.Color(204, 204, 255));
        managecustomersbtn.setText("Manage Customers Accounts");
        jPanel1.add(managecustomersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 337, -1, -1));

        signoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        signoutbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        signoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignOut.png"))); // NOI18N
        signoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        accountdetailsbtn.setBackground(new java.awt.Color(102, 0, 102));
        accountdetailsbtn.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        accountdetailsbtn.setForeground(new java.awt.Color(204, 204, 255));
        accountdetailsbtn.setText("Account details");
        jPanel1.add(accountdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 424, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminMenuResized.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void signoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutbtnActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountdetailsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageadminsbtn;
    private javax.swing.JButton manageauthorsbtn;
    private javax.swing.JButton managecompaniesbtn;
    private javax.swing.JButton managecustomersbtn;
    private javax.swing.JButton managemanagersbtn;
    private javax.swing.JButton signoutbtn;
    // End of variables declaration//GEN-END:variables
}
