/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.awt.Button;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ahmed
 */
public class ChooseUser extends javax.swing.JFrame {

    /**
     * Creates new form ChooseUser
     */
    public ChooseUser() {
        initComponents();
        admin.setOpaque(false);
        manager.setOpaque(false);
        company.setOpaque(false);
        blogauthor.setOpaque(false);
        customer.setOpaque(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        company = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        blogauthor = new javax.swing.JButton();
        manager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("login as...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 12, 300, 59));

        company.setBackground(new java.awt.Color(102, 102, 102));
        company.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        company.setForeground(new java.awt.Color(204, 0, 255));
        company.setText("company");
        company.setBorder(null);
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        jPanel1.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, 40));

        admin.setBackground(new java.awt.Color(102, 102, 102));
        admin.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(204, 0, 255));
        admin.setText("admin");
        admin.setBorder(null);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 110, 40));

        customer.setBackground(new java.awt.Color(102, 102, 102));
        customer.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        customer.setForeground(new java.awt.Color(204, 0, 255));
        customer.setText("customer");
        customer.setBorder(null);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 40));

        blogauthor.setBackground(new java.awt.Color(102, 102, 102));
        blogauthor.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        blogauthor.setForeground(new java.awt.Color(204, 0, 255));
        blogauthor.setText("blog author");
        blogauthor.setBorder(null);
        jPanel1.add(blogauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, 40));

        manager.setBackground(new java.awt.Color(102, 102, 102));
        manager.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        manager.setForeground(new java.awt.Color(204, 0, 255));
        manager.setText("manager");
        manager.setBorder(null);
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        jPanel1.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChooseUserResized.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
new AdminAddAccount().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_managerActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        new AdminMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_companyActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        new ManageAdminAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton blogauthor;
    private javax.swing.JButton company;
    private javax.swing.JButton customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manager;
    // End of variables declaration//GEN-END:variables
}
